name: CherryCore
version: '${project.version}'
main: net.cherrycraft.cherrycore.CherryCore
api-version: '1.20'
author: CherryCraft
description: CherryCore is a plugin that adds a lot of features to your server.
commands:
  language:
    description: Changes the language
  gm:
    description: Changes the game mode
  gmc:
    description: Changes the game mode to creative
  gms:
    description: Changes the game mode to survival
  gma:
    description: Changes the game mode to adventure
  gmsp:
    description: Changes the game mode to spectator
  test:
    description: Test command

