name: CherryCore
version: '${project.version}'
main: net.cherrycraft.cherrycore.CherryCore
api-version: '1.20'
author: CherryCraft
description: CherryCore is a plugin that adds a lot of features to your server.
commands:
  language:
    description: Changes the language
  test:
    description: Test command
  gm:
    description: Changes the game mode
  fly:
    description: Changes the fly mode
  vanish:
    description: Vanish command
  build:
    description: Build command
  lobby:
    description: Lobby build command
  setspawn:
    description: Sets the spawn



